### ISSUE TITLE
Setup continuous integration for JS

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/actions#5]
As of now, we're not running linting and tests as part of CI for this repo. They do run locally and have E2E tests too.

**Comment by heitorlessa** [comment]
**Caveat**. E2E test might be a problem as token might be scoped to current repository only.

To prevent a complex seed data for issues and pull requests, E2E is sourcing data from a known repository and using this repository to create/update reports.

**Comment by dreamorosi** [comment]
I'll probably tackle this in 2 separate PRs: one for linting & code quality and another for E2E.

If we need to create a GH PAT, we could consider using [@aws-powertools-bot](https://github.com/aws-powertools-bot) and give it access to that other known repo.
